### ISSUE TITLE
Do we need a parameter group metadata file?

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#105]
https://github.com/r-three/git-theta/pull/92 introduced a `.../params/metadata` file that points to what the most recent update is. However, the update directories are named via parameter hashes (not update hashes), this means that the most recent update can be inferred from the model checkpoint metadata file.

Are there other piece of metadata we will want to store in this file or can we remove it?

**Comment by blester125** [comment]
Note: As mentioned in the meeting. This file will be one that will trigger a merge conflict when branches that have touched the same parameter are merged. Is this what we want?

**Comment by nkandpa2** [comment]
Closed by #114
