### ISSUE TITLE
Include a simple short english explanation of how parameter updates work.

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#110]
Maybe some sort of (power point) animation?

**Comment by blester125** [comment]
This is maybe too detailed but should help anyone else making changes. Will add to a README with a simple explanation soon. We also probably need a (non-animated) diagram for an eventual system demo paper

![git-theta](https://user-images.githubusercontent.com/10950530/205151167-d2a93140-f477-4cc1-966f-e60790ca7c17.gif)

**Comment by craffel** [comment]
Superseded by #47
