### ISSUE TITLE
Hash parameters with an LSH (PLZ comment with thoughts)

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#115]
## The Issue

Currently we are hashing parameters based on passing their `.tobytes` value to a hash function (sha-1 atm). This works when parameters are **exactly** the same. This will start to cause issues when we begin to use parameter efficient updates. There are basically 2 places where this issue can arise:

1) Communication Efficient Update inference: When back-calculating things, (like a low-rank update based on the previous and current value via SVD) we can find update values that result in close parameters (i.e. they pass `np.allclose` even with stricter than default `rtol` and `atol` settings) that don't pass hash equality (i.e. `hash(current) != hash(previous + update)`). Depending on what parameter hash we store in the metadata file we will either have git reporting a diff right after a checkout or the hash in the metadata file won't actually match the hash of the parameters created during smudge. 
* This also opens the door for a systematic divergence between the checked in parameters and the working dir parameters. If the working dir parameters are never smudged then the each change will be from a different starting point and the communication efficient update will be calculated based on a different previous value than the training update was made with.

2) Communication Efficient Update application: The second place where you could get issues is in the application of updates on different machines i.e. when a smudge happens when checking out a repo on a new machine. Things that are non-deterministic can result in small amounts of noise to the point where it passes `np.allclose` but not hash equality. This will result in `git checkout && git status|diff` reporting changes in the checkpoint file.

## Solutions

`np.allclose` is non-transitive so we can't design a hash function where np.allclose equality implies hash equality and actually using `np.allclose` for equality checks will result in many unnecessary reads.

Instead we can use a Locality Sensitive Hash (LSH) to hash parameter values. LSH's are designed so that similar items hash together. Their main use-case is cheap similarity search based on the sketch (`LSH(real_value)`) but using that sketch as our hash bucket should result in hash equality when the parameter values are close to each other, even if they aren't an exact match. Most LSH's also have parameters that let you tune the how well they approximate the true similarity functions (at the cost of taking extra space) so we should be able to configure the LSH to be reasonable sure we can avoid collisions.

### Random Hyperplanes

One LSH that approximates cosine difference is the Random Hyperplanes approach. Multiple random plans are drawn, the dot product between the plan and the item is calculated and the sign of the result recorded to create a signature. Then $$\cos(\theta_{a, b}) \approx \cos(\frac{h}{b} \pi) $$ where $h$ is the hamming distance between the two signatures and $b$ is the length of the signature. So we can set the number of hyperplanes by thinking, $b$ hyperplanes means all tensors with an angle  $< \frac{1}{b}\pi$ will hash together. And we can run some experiments on real models + noise/small updates to help set this value.

I have a simple implementation [here](https://github.com/blester125/quick_knn) but there are also better versions (see the pooling version) discussed [here](https://www.cs.cmu.edu/~wcohen/10-605/randomized-algs-3-lsh.pdf)

### Quantization

Another idea was to run quantization on the tensors, converting them integer tensor buckets. Then doing a normal hash on them. There are various setting in quantization algorithms to should allow us to adjust how close parameters are before they are bucketed together.

_Note:_ We need to keep the LSH consistent across commits (i.e. unchanged parameter group 1 needs to have the same signature each commit so we can compare them over time) so we will need to either store the LSH state somewhere or have it be reproducible based on some seed setting.

**Comment by blester125** [comment]
I did some research over the weekend, basically I think using an LSH is the principled way to approach this, but there are a few open questions.

## Why an LSH

The theory of LSHs gives us knobs to adjust the probabilities of true and false positives. The core hash family (random hyperplanes, minhash, etc) used is $(d_1, d_2, p_1, p_2)-\text{sensitive}$ meaning that if $\text{distance}(x, y) \leq d_1 \rightarrow \Pr[h(x) = h(y)] \geq p_1$ and if $\text{distance}(x, y) \geq d_2 \rightarrow \Pr[h(x) = h(y)] \leq p_2$. Then we can use a technique called "banding" to drive $p_1$ towards $1$ and $p_2$ towards $0$.

This means we can choose a distance where we want two parameters that are closer than that to "hash equal" and further "hash different". We then choose signature lengths and banding parameters and have probabilistic bounds on if we expect collisions.

Some LSH families (for example HyperPlanes for Cosine Distance) have alternate implementations (i.e. random projections with a pool) what lets us hash variable length parameters and have a "distance" even if we can't take an actual cosine distance between the parameters.

## Open Questions

I think the biggest questions for this approach are based on the unknowns of how numerical noise like this effects models.

1) What is a sensible "distance" metric for parameter weights? What captures changes that we expect to result in model changes?
2) Given a distance metric, what is a good cutoff on distance to consider things equal? Is this just really small or is this based off the distance that will cause changes in model outputs?
3) What kind of effects to numerical noise have on predictions/intermediate values in networks? Should we run a few different models in different settings and collect and compare these sorts of things or can we set reasonable values ourselves?

**Comment by nkandpa2** [comment]
With something like the cosine LSH does it disregard all magnitude information and only take into account angle?

**Comment by blester125** [comment]
1) Yeah, the cosine LSH is only about the angle. It is unclear if that is bad (i.e. does angle or magnitude or both correlate the most with changes in the output space)
2) The hamming distances between 2 LSH hashes can be used to estimate the cosine distance so it could probably be used in like you mentioned.
3) Size of parameters depends on the size of the signatures (hash output size) which is a factor of the fp/fn probabilities we want. But the cosine one is `signature_size * 4 + pool_size * 4` where generally signature size $\in [32, 256]$ and pool size $\approx 10{,}000$ so I would guess $\approx 4\text{Kb}$

**Comment by craffel** [comment]
Plan: Use the three-stage LSH-based comparison; if the parameter group has changed, indicate the level of change in git-diff. Still need to explore different LSH options.
