### ISSUE TITLE
Respect `$XDG_CONFIG_HOME`

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#122]
Currently we use a function `git.config.get_config_path` from `GitPython` to find the global configuration file.

The library doesn't follow the way git picks between `~/.gitconfig` or `$XDG_CONFIG_HOME/git/config`, instead `"global"` always selects `~/.gitconfig` 

We should create our own function that follow git (see below) and use that. We could also try to upstream the change to GitPython

```
For writing options: write to global ~/.gitconfig file rather than the repository .git/config, write to $XDG_CONFIG_HOME/git/config file if this file exists and the ~/.gitconfig file doesn’t.

For reading options: read only from global ~/.gitconfig and from $XDG_CONFIG_HOME/git/config rather than from all available files.
```

**Comment by craffel** [comment]
+1 to upstreaming the change since this seems like a missing feature of GitPython

**Comment by craffel** [comment]
@blester125 is going to open an issue on GitPython .

**Comment by blester125** [comment]
Note: GitPython now has support (or I missed it last time lol) for this with the new `user` level of configuration https://github.com/gitpython-developers/GitPython/blob/fe1934c5c90e617d49a38a6c36b1eb17dea47013/git/repo/base.py#L581
