### ISSUE TITLE
Markdown autoformat pre-commit

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#123]
Add some markdown formatting/linting library as a pre-commit check and as a CI check.

IIRC we also discusses using documentation generation (like sphinx) in CI as a way to do part of the documentation linting. Not sure if that would cover markdown like this or just docstrings.

**Comment by craffel** [comment]
If we choose to use Sphinx for generating docs, we can include doc generation as a CI check. I've used Sphinx in the past but with ReST, which was kind of awful. I think Sphinx supports Markdown but I haven't tried it. https://blog.readthedocs.com/adding-markdown-support/
There are also some markdown-based documentation generation libraries I haven't tried, e.g. 
https://github.com/NiklasRosenstein/pydoc-markdown
https://github.com/tomchristie/mkautodoc

**Comment by craffel** [comment]
#197 will cover the doc building, @blester125 will add a pre-commit for markdown linting for non-docstrings (like README).
