### ISSUE TITLE
Make real sparse updates.

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#125]
Currently the sparse update implementation doesn't create an actually sparse difference, it is a dense representation (regardless of the number of 0's). Update it to actually use a sparse matrix format (scipy CSR or similar)

Main changes are:

1) [`SparseUpdate.calculate_update`](https://github.com/r-three/git-theta/blob/8222c05a960074f21ed758f27c87613a274862a7/git_theta/updates/sparse.py#L17) should be updated to return an actual sparse update. 
2) `SparseUpdate` should override `write_update` to break the sparse matrix into a dict of `{"indices": [...], "values": [...]}"` which it then passes to `super().write_update(...)`
3) `SparseUpdate` should override `read` to call `super().read()` and then stitch the dict back into a sparse tensor value.

`SparseUpdate.apply_update` should not need to be updated as numpy polymorphism should be able to handle it but we'll want to verify that.

**Comment by blester125** [comment]
You might also need to make these changes

```diff
diff --git a/git_theta/updates/base.py b/git_theta/updates/base.py
index 4933144..eceab84 100644
--- a/git_theta/updates/base.py
+++ b/git_theta/updates/base.py
@@ -35,8 +35,8 @@ class Update(metaclass=ABCMeta):
         """Read in and deserialize a single parameter value based metadata."""
         lfs_pointer = param_metadata.lfs_metadata.lfs_pointer
         serialized_param = await git_utils.git_lfs_smudge(lfs_pointer)
-        param = (await self.serializer.deserialize(serialized_param))["parameter"]
-        return param
+        param = (await self.serializer.deserialize(serialized_param))
+        return param.get("parameter", param)
 
     @abstractmethod
     async def write(
@@ -114,7 +114,9 @@ class IncrementalUpdate(Update):
 
     async def write_update(self, update: Parameter) -> metadata.LfsMetadata:
         """Save and serialize (just) the update weights."""
-        serialized_update = await self.serializer.serialize({"parameter": update})
+        if not isinstance(update, dict):
+            update = {"parameter": update}
+        serialized_update = await self.serializer.serialize(update)
         lfs_pointer = await git_utils.git_lfs_clean(serialized_update)
         return metadata.LfsMetadata.from_pointer(lfs_pointer)
```

**Comment by muqeeth** [comment]
class SparseUpdate(IncrementalUpdate):
    """An update where only some parameters are touched."""

    @property
    def name(self):
        return "sparse"

    async def calculate_update(
        self, parameter: Parameter, previous_parameter: Parameter
    ) -> Parameter:
        return csr_matrix(parameter - previous_parameter)
    
    async def write_update(self, update: Parameter) -> metadata.LfsMetadata:
        """Save and serialize (just) the update weights."""
        rows, cols = update.nonzero()
        vals = [update.data[i] for i in range(len(rows))]
        sparse_dict = {"rows": rows, "columns": cols, "values": vals}
        super().write_update(sparse_dict)

    async def read(self, param_metadata: metadata.ParamMetadata) -> Parameter:
        """Read in and deserialize a single parameter value based metadata."""
        lfs_pointer = param_metadata.lfs_metadata.lfs_pointer
        serialized_param = await git_utils.git_lfs_smudge(lfs_pointer)
        param = (await self.serializer.deserialize(serialized_param))

        return csr_matrix(param.get("values", param), (param.get("rows", param), param.get("columns", param)))

    async def apply_update(self, update: Parameter, previous: Parameter) -> Parameter:
        return update + previous

I made the following changes, can you please comment on it?
I have few questions:
1. If read method always returns sparse tensors, can apply_update method add sparse tensor to a dense one at some point?
2. Our method doesn't work if the weight parameters are 3d tensors, as write_update method has only rows and columns stored, right?
3. I know csr_matrix works on numpy arrays, I will need to see if it works on tensors. Does the parameter variable in this class, a tensor or a numpy object or can be anything?

**Comment by blester125** [comment]
A sketch of how to do this using tensorflows sparse tensor which supports ND tensors in a way that scipy doesn't.  

Another option is to save the shape of the dense tensor, flatten it, convert to scipy sparse and make the dict with dense shape, dict, and indices. Then during load we make a sparse array and reshape/densify it.

Given that we are using the sparse matrix to save data on the wire (not to make some huge sparse array fit in memory at all) I think we are fine to convert to dense matrices before addition to the previous value so we don't need to care about the exact format of the sparse tensor (which normally effects how efficient *using* the sparse tensor is)

Does anyone have options on what is a better dep to bring in for sparse support TF vs Scipy? @nkandpa2 @craffel 

```python
import tensorflow as tf
import numpy as np

# The actual update value
x = np.array([[[1, 0, 0], [0, 1, 0]], [[0, 0, 1], [1, 0, 1]]])

# In the calculate update method
y = tf.sparse.from_dense(tf.convert_to_tensor(x))
dict_y = {"values": y.values.numpy(), "indices": y.indices.numpy(), "dense_shape": y.dense_shape.numpy()}
# this disk is what is saved to disk

# In the apply update method
# Convert from the dict into a sparse tensor
new_y = tf.SparseTensor(**dict_y)
# Convert back to numpy
new_x = tf.sparse.to_dense(new_y).numpy()

# We have round tripped it!
np.testing.assert_allclose(x, new_x)
```

```python
import scipy.sparse
import numpy as np

x = np.array([[[1, 0, 0], [0, 1, 0]], [[0, 0, 1], [1, 0, 1]]])

# In calculate update
shape = x.shape
y = scipy.sparse.csr_matrix(np.reshape(x, (-1,)))
dict_y = {"data": y.data, "indices": y.indices, "indptr": y.indptr, "shape": shape}

# In the apply update method
new_y = scipy.sparse.csr_matrix((dict_y["data"], dict_y["indices"], dict_y["indptr"]))
new_x = np.reshape(new_y.toarray(), dict_y["shape"])

# We have round tripped it!
np.testing.assert_allclose(x, new_x)
```

**Comment by nkandpa2** [comment]
I would tend to go with scipy since (I think?) it's a lighter weight dependency than TF.

**Comment by blester125** [comment]
This was finished in https://github.com/r-three/git-theta/pull/128
