### ISSUE TITLE
Sparse Thresholding

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#129]
We need to decide if we want to threshold small (`1e-12`, etc) values to 0 before passing to the sparse matrix as it only checks for actual zeros.

**Comment by blester125** [comment]
For now, have the threshold be an `__init__` parameter with a `# TODO` to make it configurable

**Comment by muqeeth** [comment]
class SparseUpdate(IncrementalUpdate):
        """An update where only some parameters are touched."""
        def __init__(self, serializer: params.Serializer, threshold: Optional[float] = 1e-12):
            # TODO: Make threshold configurable
            super().__init__(serializer)
            self.threshold = threshold        

    @property
    def name(self):
        return "sparse"

    async def calculate_update(
        self, parameter: Parameter, previous_parameter: Parameter
    ) -> Parameter:
        diff = parameter - previous_parameter
        diff[np.abs(diff) < self.threshold] = 0
        # csr_matrix looks for actual zeros in diff tensor. We can consider adding threshold option on diff tensor in future
        update = scipy.sparse.csr_matrix(np.reshape(diff, (1, -1)))
        return {
            "data": update.data,
            "indices": update.indices,
            "indptr": update.indptr,
            "shape": parameter.shape,
        }

    async def apply_update(self, update: Parameter, previous: Parameter) -> Parameter:
        # Provide shape of original flattened array to ensure correct shape of output. Without the provided shape, csr_matrix interprets the shape as (1, index of last occurence of a non-zero number in the original flattened array)
        param_update = scipy.sparse.csr_matrix(
            (update["data"], update["indices"], update["indptr"]),
            shape=(1, np.prod(update["shape"])),
        )
        return np.reshape(param_update.toarray(), update["shape"]) + previous


This should be good right @blester125 ?

**Comment by blester125** [comment]
Yeah, you should also update the comment on `csr_matrix` looking for zeros to be above the threshold line and update the text to explaining why we threshold instead of thinking about thresholding.

Also it would be easier to make a PR instead of pasting in the issue this so people can comment with github's code review tools.

**Comment by muqeeth** [comment]
Great, I will make a PR with the changes
