### ISSUE TITLE
Detect and Error when Git-LFS is not installed

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#134]
When running git theta install we should have a check that git lfs is installed. If it is not we should abort the git-theta install.

Currently running commiting a model with git-theta and no git-lfs results is very esoteric errors about unicode encoding errors.

**Comment by muqeeth** [comment]
how do we go about doing this? Can we run a command inside git-theta install function to see if git-lfs is installed?

**Comment by blester125** [comment]
Yeah you should be able to use `subprocess.run` to run something like `git lfs --version` and then check the return code. If it is not zero throw then they don't have it installed.
