### ISSUE TITLE
Verify Merge Behavior with multiple commits on a branch.

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#135]
Ensure that when merging branches with multiple commits that our merge tool still works.

Figure out things like, "Do we end up merging the files multiple times (one for each commit in the branch)?"

**Comment by blester125** [comment]
From the git documentation

```
With the strategies that use 3-way merge (including the default, ort)
...
only the heads and the merge base are considered when performing a merge, not the individual commits.
```

So we should be ok, but I we should add a test case that covers this.

**Comment by craffel** [comment]
Great, thanks for clarifying - I must have been thinking of rebases. I don't think there'd be a good way to do "take mine for all commits in this rebase", right?

**Comment by blester125** [comment]
There maybe.

Merge *strategies* are tools that decide *what* to merge and the default one called `ort` has an option called [`ours`](https://git-scm.com/docs/merge-strategies#Documentation/merge-strategies.txt-ours) where anything touched by both branches always results taking the change from the current branch. This seems to be a chunk level approach allowing for changes from branch B to be applied, as long as they don't conflict with changes from A.

There is also a strategy called [`ours`](https://git-scm.com/docs/merge-strategies#Documentation/merge-strategies.txt-ours-1) which seems to totally ignore **all** changes from the other branch which seems harsher than what you are aiming for? (their example is your remote branch have a different config file for the dev-instance and you don't want to try to merge that with the prod-instance config on your main branch)

**Comment by blester125** [comment]
Rebase support tracked in https://github.com/r-three/git-theta/issues/140
