### ISSUE TITLE
User-facing memory ↔ git-theta save/load methods

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#210]
# Git Theta for Tracking Models Over a Training Run.

## Naive Implementation and Extra IO issue

We talked about the use case of using git-theta to track an experiment over the course of training. The simplest way to do this is like:

```python
m = BriansSuperCoolModel()
...
for batch in dataset:
  train_step(m, ..)
  ...
  if perf > best_perf:
    torch.save(m.state_dict(), "path/to/ckpt")
    sha = git_theta.commit("path/to/ckpt")
    best = sha
  ...
  
git_theta.checkout(best)
m = torch.load("path/to/ckpt")
run_eval(m)
```

We discussed ways to make things like committing non-blocking and hide that from the user, but the main issue we though of was that there are now extra reads and writes. Saving in now a torch native write in the training loop and a torch native read 
and git-theta write in the commit. Similarly loading is now a git-theta read and a torch native write in the checkout and a torch native read in the training loop.

## Git Theta Direct Storage Solution

A solution we had is to have direct memory $\iff$ git-theta transfer to avoid these double writes. We would create user facing functions like `git_theta.save|load` (or better names :woman_shrugging:?) and the loop would look something like this.

```python
m = MuqeethsEvenCoolerModel()
...
for batch in dataset:
  train_step(m, ...)
  ...
  if perf > best_perf:
    best = git_theta.save(m.state_dict(), "path/to/ckpt")
  ...

m = git_theta.load(best)
run_eval(m)
```

The advantages of this is that we would skip the extra reads and writes by not materializing the checkpoints on the file system.

### Efficient partial updates

We think this approach would also enable efficient storage of partial model updates without having to write unchanged parameters. For example, if only the decoder is updated in an EncDec model, when we call `git_theta_save` the parameter equality checks would make it so that only the decoder weights are added as git-lfs objects.

## Open Questions

* Should `git_theta.save` commit the model our just add it?
    * What happens to the working tree when you programatically make a commit? Does it get updated or do you end up in a detached HEAD state?
        * **The repo will be at the new commit which is now HEAD, but the file that was committed will not be in the working tree so a `git status` will show it as deleted.**
            * This means we may want to add a `git_theta.load(..., checkout=True)` flag that will actually smudge the model to disk? Then if they use this at the end of training they will have a model on disk and the repo will be at the commit for that model?
* How do we make this non-blocking and hide it from the user?
    * We have control of the path object and sha objects, we could make them futures where `git_theta.load` will block until saving it done if it gets an unfinished `best` future?
    * How to handle save? We pretty quickly turn tensors into numpy arrays (do these share memory or will be be creating to copies of the model? If it is a copy it should be CPU so not a huge issue?) so we might be fine to let them keep training? In training would cause values to change we may need to make these blocking.
* Do we need any special handling for tensors that live on GPU?
    * **We already have `.cpu()` calls when models are loaded with pytorch so I think we just need to have to do something similar.**
* Do we have an issue with checkout if this is used for for training multiple tasks in parallel experiments? i.e. I have `pre-trained.pt` and want to train it on `sst2` and `boolq` by tuning the final layer. I train with `git_theta.save|load` so I have never materialized `sst2.pt` or `boolq.pt` but they are both committed. I now checkout `HEAD` and have to smudge two huge models (which can take a while).
    * So we have solved having multiple copies of the pre-trained parameters during training and saving but not at the end (i.e. if I had separate saved head parameters the working tree would be really small)
    * Do we want to add something like `git_theta.checkout(no_smudge=True)` where we can decide which models are smudged? Lets us keep the working dir small for when we only want a single model at a time but would still be big if we want access to all models.
    * Or kick this to the user and say if you want multiple PEM models in the working tree efficiently you need to have code that can handle multiple parameter files?
* Git commit hashes are not user friendly, we need some sort of tooling to make this easier for people
    * Maybe something like a `git_theta_experiments` layer where you can associate metadata with a commit and then do queries like `SELECT BEST(acc) FROM "path/to/ckpt"` and it returns the sha. Wouldn't necessarily want to make a git-theta-SQL dialect lol.
* Do we need to provide a way to prune history? Often you may save many checkpoints (for preemption, eval, etc.) but only want a few that you save forever.
    * Similarly people often have something like "save-last-n" checkpoints which we may want to support?
        * If we get rebase working (and it is cheap?) we could so something cool like saving makes a temp branch and once we hit n commits, the n+1 commit creates a new branch, rebases all commit save the first one onto that, and deletes the old branch. Super cool but complex?

**Comment by craffel** [comment]
This is cool - it would be great to be able to avoid the extra reads/writes to disk. Can you expand on how #211 resolves some of the questions you mentioned above? I personally have definitive answers to the questions you asked above - I think most of them depend on whether/how we can implement things in a way that keeps things non-blocking from the perspective of the user. The only exceptions are these questions:
> Git commit hashes are not user friendly, we need some sort of tooling to make this easier for people
> Maybe something like a git_theta_experiments layer where you can associate metadata with a commit and then do queries like SELECT BEST(acc) FROM "path/to/ckpt" and it returns the sha. Wouldn't necessarily want to make a git-theta-SQL dialect lol.

and

> Do we need to provide a way to prune history? Often you may save many checkpoints (for preemption, eval, etc.) but only want a few that you save forever.
> Similarly people often have something like "save-last-n" checkpoints which we may want to support?
 > If we get rebase working (and it is cheap?) we could so something cool like saving makes a temp branch and once we hit n commits, the n+1 commit creates a new branch, rebases all commit save the first one onto that, and deletes the old branch. Super cool but complex?

I'd preliminarily suggest not doing these things as part of the core git-theta package. We don't want git-theta to become an experiment tracker/management system; we want it to do one thing (git extension for checkpoints) and do it well. It would be better I think if we just made sure it was possible to easily build the functionality you mentioned into additional tools that can sit as a layer on top of git-theta.

**Comment by craffel** [comment]
> The repo will be at the new commit which is now HEAD, but the file that was committed will not be in the working tree so a git status will show it as deleted.

This seems really odd, right? I think a use might panic if they ran `.save` and then did a `git status` and were told the file was deleted.

**Comment by blester125** [comment]
That makes sense, it would mean we can't avoid having to write the full checkpoint all the time though.

Maybe we should have a `materialize` flag but default to `True` and then they can set it to false for gains if they understood that is what they would see?

**Comment by craffel** [comment]
Maybe this is a ridiculous idea, but is there any way we could trigger materialization of the checkpoint lazily or something?

**Comment by blester125** [comment]
You mean like it would happen if they run `git status`?

If we think people will be worried their checkpoint is missing, something like that wouldn't solve the case of them looking at the working tree and not seeing it.

We should be able to make materialization non-blocking at least

**Comment by muqeeth** [comment]
> That makes sense, it would mean we can't avoid having to write the full checkpoint all the time though.
> 
> Maybe we should have a `materialize` flag but default to `True` and then they can set it to false for gains if they understood that is what they would see?

Why would `git status` show the file as deleted? I was under the impression that the file exists in the working tree but has outdated content compared to the staging area. In that case, wouldn't `git status` show the file as modified instead of deleted?

**Comment by blester125** [comment]
Sorry, I was being imprecise. `git status` will show different things based on the working tree, in the situation you are describing it would show a diff. In my setting I was saving it with a path that never existed in the working tree so it showed deleted.
