### ISSUE TITLE
Parameter groups that are more than just tensors?

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#218]
Should we make sure that our logic is able to handle parameter groups that are more than a single tensor? For example if I defined a "parameter group" to be both the weight and the bias in a feed forward layer (because I want to get a bit of boost from using a larger file or because I don't want them to be changed independently) our code could be able to hash, serialize, save, etc this collection of tensors as a single group?

We already have something similar in how updates with multiple values are serialized. This shouldn't be too difficult to implement with something like jax's `tree_map` abstraction.

**Comment by craffel** [comment]
I really like the abstraction of "parameter group is a single tensor". Apart from convenience in terms of grouping things in other semantically-meaningful ways, is there any other benefit?

**Comment by blester125** [comment]
I didn't have a clear use-case, was just thinking about how one review asked how the groups were identified. That is part of the checkpoint plugin so technically it is currently user-overrideable.

Also some of the update classes processes dicts instead of single tensors (i.e. the two matrices in LoRA or the index and value in sparse updates) which have special code to deal with that. If all code could transparently do that it could simplify things.

I was mostly posting to see if someone else had a good use-case for it lol.
