### ISSUE TITLE
Method to tell if git-theta wasn't installed?

### ISSUE THREAD

**Issue by blester125** [r-three/git-theta#229]
There have been a couple of times where I have showed git-theta to new people and I forget to tell them they need to run `git theta install`.

When you forget to install it, `git theta track` works as normal, but when you run `git add` the filters definitions aren't found and git silently just does a normal add.

Would it be possible/make sense to add an install check in the track command or something to avoid it?

**Comment by craffel** [comment]
Yes!

**Comment by blester125** [comment]
One situation that is still challenging is if someone doesn't have git-theta installed and they clone a git-theta repo. Because they don't have it installed, none of our hooks/filters will be setup so their clone/pull will result in them getting a git-theta metadata file on disk instead of a the real checkpoint.

Similarly, if the model file is already tracked, they won't be running `git theta track` so there isn't a chance to detect they haven't installed git theta and their `git add ` will not use our filter and they will end up staging the original model checkpoint. If they run `git theta add` (because they pip installed but never run `git theta install`) we could detect this issue, but that wouldn't follow our "its just like git" messaging if we recommended using `git theta add` over `git add`. This might be an unwinnable situation, but would like to hear anyone's thoughts.

**Comment by craffel** [comment]
Hmm... I can't really think of a way of handling the issue where someone closes a git-theta repo without having git-theta installed. Wouldn't this also be an issue for e.g. git-lfs?
