### ISSUE TITLE
Add basic integration tests

### ISSUE THREAD

**Issue by craffel** [r-three/git-theta#51]
Add a simple test that creates a pytorch checkpoint and does as few operations on it; set up continuous integration to run it.

**Comment by blester125** [comment]
This might inform how the tests are run/written, but I think one thing we should be testing for is when not everything is in the current working dir. At a minimum I think we should be testing:

* Git commands run from root of repo
  * Checkpoint is also in the repo root
  * Checkpoint is in a subdir of the repo
* Git commands run from a sub dir of the repo
  * checkpoint is in cwd
  * checkpoint is elsewhere (parent, sub dir, sibling not sure how exhaustive we should be)
